---

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - aspell
  - autoconf
  - black
  - docker-completion
  - docker-compose-completion
  - flake8
  - gdbm
  - gettext
  - go
  - go-task
  - helm
  - kubernetes-cli
  - minikube
  - node
  - nomad
  - openssl
  - packer
  - packer-completion
  - pcre
  - pipenv
  - pulumi
  - pyenv
  - pyenv-virtualenv
  - python
  - sqlite
  - terraform
  - terragrunt
  - tflint
  - thefuck
  - tree
  - vault
  - watch
  - wine

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - discord
  - protonmail-bridge
  - protonvpn
  - sublime-merge
  - sublime-text
  - transmit
  - vagrant
  - visual-studio-code
