---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']

  tasks:
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/firacode.yml
      tags:
       - download_only
       - font_install